# 服务端口
server:
  port: ${gateway_server_port:10000}

# 注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
  instance:
    # 使用 ip 代替实例名
    prefer-ip-address: false

security:
  gw:
    # 请求头 referer 配置
    referer:
      enabled: ${security_gw_referer_enabled:true}
      ignoreHosts:
        - ${security_gw_referer_ignoreHosts}
      whiteList:
        - ${security_gw_referer_whiteList}

spring:
  application:
    name: micro-rcms-gateway-server
  profiles:
    active: loc
  cloud:
    gateway:
      routes:
        # 路由的ID,没有固定规则但要求唯一,建议配合服务名
        - id: auth-service
          # 匹配后提供服务的路由地址
          uri: http://localhost:9090
          # 断言,路径相匹配的进行路由
          predicates:
            - Path=/authApi/**
          filters:
            - PrefixPath=/lbs
            # 请求添加参数age=18
            - AddRequestParameter=t,18
        - id: tmdb-service
          # 匹配后提供服务的路由地址
          uri: http://localhost:52602
          # 断言,路径相匹配的进行路由
          predicates:
            - Path=/com.stone.it:tmdb/tmdbApi/**
          filters:
            #去掉路径前缀
            - StripPrefix=1
            #- RewritePath=/com.stone.it:tmdb,""
            # 请求添加参数age=18
            - AddRequestParameter=desc,18


