--  国际化信息
CREATE TABLE IF NOT EXISTS `tpl_i18n_t`(
    `I18N_ID`      VARCHAR(100) NOT NULL COMMENT 'KEY',
    `I18N_KEY`    VARCHAR(200) NOT NULL COMMENT 'KEY',
    `I18N_NAME`   VARCHAR(1000)          NOT NULL COMMENT 'NAME',
    `LANGUAGE`   VARCHAR(1000)          NOT NULL COMMENT 'LANGUAGE',
    `CREATED_TIME` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `CREATED_BY`   varchar(100) NOT NULL DEFAULT 'UNKNOWN',
    `UPDATED_TIME` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_BY`   varchar(100) NOT NULL DEFAULT 'UNKNOWN',
    PRIMARY KEY (`I18N_ID`)
    ) ENGINE = InnoDB
    DEFAULT CHARSET = utf8mb4;

-- LOOK UP CLASSIFY
CREATE TABLE IF NOT EXISTS `tpl_classify_t`(
    `CLASSIFY_CODE`    VARCHAR(200) NOT NULL COMMENT 'CLASSIFY_CODE',
    `CLASSIFY_NAME`   VARCHAR(200)          NOT NULL COMMENT 'CLASSIFY_NAME',
    `DESCRIPTION`   VARCHAR(1000)          NOT NULL COMMENT 'DESCRIPTION',
    `CREATED_TIME` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `CREATED_BY`   varchar(100) NOT NULL DEFAULT 'UNKNOWN',
    `UPDATED_TIME` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_BY`   varchar(100) NOT NULL DEFAULT 'UNKNOWN',
    PRIMARY KEY (`CLASSIFY_CODE`)
    ) ENGINE = InnoDB
    DEFAULT CHARSET = utf8mb4;

-- LOOK UP ITEM
CREATE TABLE IF NOT EXISTS `tpl_item_t`(
    `ITEM_ID`    VARCHAR(100) NOT NULL COMMENT '唯一ID',
    `ITEM_CODE`    VARCHAR(200) NOT NULL COMMENT '取值编码',
    `ITEM_NAME`    VARCHAR(500) NOT NULL COMMENT '显示名称',
    `LANGUAGE`    VARCHAR(50) NOT NULL COMMENT '语言',
    `ITEM_INDEX`    VARCHAR(100) NOT NULL COMMENT '排序值',
    `IS_ENABLED`    VARCHAR(10) NOT NULL COMMENT '是否开启',
    `DESCRIPTION`    VARCHAR(1000) NOT NULL COMMENT 'DESCRIPTION',

    `ITEM_ATTR1`    VARCHAR(1000) NOT NULL COMMENT '备用字段1',
    `ITEM_ATTR2`    VARCHAR(1000) NOT NULL COMMENT '备用字段2',
    `ITEM_ATTR3`    VARCHAR(1000) NOT NULL COMMENT '备用字段3',
    `ITEM_ATTR4`    VARCHAR(1000) NOT NULL COMMENT '备用字段4',
    `ITEM_ATTR5`    VARCHAR(1000) NOT NULL COMMENT '备用字段5',

    `CREATED_TIME` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `CREATED_BY`   varchar(100) NOT NULL DEFAULT 'UNKNOWN',
    `UPDATED_TIME` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_BY`   varchar(100) NOT NULL DEFAULT 'UNKNOWN',
    PRIMARY KEY (`ITEM_ID`)
    ) ENGINE = InnoDB
    DEFAULT CHARSET = utf8mb4;

-- 用户主表
CREATE TABLE IF NOT EXISTS `tpl_user_t`(
    `USER_ID`       VARCHAR(100)     NOT NULL ,
    `USER_ACCOUNT`    VARCHAR(100) NOT NULL COMMENT '用户账号',
    `USER_NAME`    VARCHAR(100) NOT NULL COMMENT '用户名称',
    `PASSWORD`    VARCHAR(100) NOT NULL COMMENT '用户密码',
    `CREATED_TIME` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `CREATED_BY`   varchar(100) NOT NULL DEFAULT 'UNKNOWN',
    `UPDATED_TIME` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_BY`   varchar(100) NOT NULL DEFAULT 'UNKNOWN',
    PRIMARY KEY (`USER_ID`)
    ) ENGINE = InnoDB
    DEFAULT CHARSET = utf8mb4;

-- 栏目表
CREATE TABLE IF NOT EXISTS `tpl_site_t`(
   `SITE_ID`    VARCHAR(100) NOT NULL COMMENT '栏目ID',
   `SITE_CODE`    VARCHAR(100) NOT NULL COMMENT '栏目编码用于关联国际化',
   `SITE_NAME`    VARCHAR(1000) NOT NULL COMMENT '默认栏目名称',
   `SITE_URL`    VARCHAR(100) NOT NULL COMMENT '访问URL',
   `IS_PUBLISH`    VARCHAR(100) NOT NULL COMMENT '是否发布',
   `OPEN_WAY`    VARCHAR(100) NOT NULL COMMENT '打开方式',
   `CREATED_TIME` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `CREATED_BY`   varchar(100) NOT NULL DEFAULT 'UNKNOWN',
   `UPDATED_TIME` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `UPDATED_BY`   varchar(100) NOT NULL DEFAULT 'UNKNOWN',
   PRIMARY KEY (`SITE_ID`)
   ) ENGINE = InnoDB
   DEFAULT CHARSET = utf8mb4;


