-- 企业表 done
CREATE TABLE IF NOT EXISTS `tpl_enterprise_t`(
    `parent_id`      VARCHAR(100)  COMMENT '父节点ID，为空表示根节点',
    `enterprise_id`      VARCHAR(100) NOT NULL COMMENT '企业ID',
    `enterprise_code`    VARCHAR(100) NOT NULL COMMENT '企业编码',
    `enterprise_name`    VARCHAR(100) NOT NULL COMMENT '企业名称',
    `enterprise_type`    VARCHAR(30) NOT NULL COMMENT '企业类型:platform/enterprise/merchant',
    `CREATED_TIME` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `CREATED_BY`   varchar(100) NOT NULL DEFAULT 'UNKNOWN',
    `UPDATED_TIME` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_BY`   varchar(100) NOT NULL DEFAULT 'UNKNOWN',
    PRIMARY KEY (`enterprise_id`)
    ) ENGINE = InnoDB
    DEFAULT CHARSET = utf8mb4;

-- 角色表 done
CREATE TABLE IF NOT EXISTS `tpl_role_t`(
    `enterprise_id`      VARCHAR(100) NOT NULL COMMENT '企业ID',
    `parent_code`    VARCHAR(100) NOT NULL COMMENT '父节点ID，为空表示根节点',
    `ROLE_CODE`    VARCHAR(100) NOT NULL COMMENT '角色CODE',
    `ROLE_NAME`    VARCHAR(100) NOT NULL COMMENT '角色名',
    `DESCRIPTION`    VARCHAR(100) NOT NULL COMMENT '描述',
    `CREATED_TIME` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `CREATED_BY`   varchar(100) NOT NULL DEFAULT 'UNKNOWN',
    `UPDATED_TIME` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_BY`   varchar(100) NOT NULL DEFAULT 'UNKNOWN',
    PRIMARY KEY (`ROLE_CODE`)
    ) ENGINE = InnoDB
    DEFAULT CHARSET = utf8mb4;

-- 权限表 done
CREATE TABLE IF NOT EXISTS `tpl_permission_t`(
    `permission_code`    VARCHAR(100) NOT NULL COMMENT '权限编码',
    `api_path`    VARCHAR(100) NOT NULL COMMENT '接口地址',
    `api_name`    VARCHAR(100)  COMMENT '接口名称',
    `api_type`    VARCHAR(100) NOT NULL COMMENT '接口类型：system/custom',
    `request_type`    VARCHAR(100) NOT NULL COMMENT '请求方式',
    `DESCRIPTION`    VARCHAR(100) NOT NULL COMMENT '描述',
    `CREATED_TIME` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `CREATED_BY`   varchar(100) NOT NULL DEFAULT 'UNKNOWN',
    `UPDATED_TIME` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_BY`   varchar(100) NOT NULL DEFAULT 'UNKNOWN',
    PRIMARY KEY (`permission_code`)
    ) ENGINE = InnoDB
    DEFAULT CHARSET = utf8mb4;

-- 角色权限关系表 done
CREATE TABLE IF NOT EXISTS `tpl_role_permission_t`(
    `role_code`    VARCHAR(100) NOT NULL COMMENT '角色编码',
    `permission_code`    VARCHAR(100) NOT NULL COMMENT '权限编码',
    `CREATED_TIME` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `CREATED_BY`   varchar(100) NOT NULL DEFAULT 'UNKNOWN',
    `UPDATED_TIME` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_BY`   varchar(100) NOT NULL DEFAULT 'UNKNOWN',
    PRIMARY KEY (`role_code`,`permission_code`)
    ) ENGINE = InnoDB
    DEFAULT CHARSET = utf8mb4;

-- 账户表 done
CREATE TABLE IF NOT EXISTS `tpl_account_t`(
    `account_code`    VARCHAR(100) NOT NULL COMMENT '账户登录',
    `account_name`    VARCHAR(100) NOT NULL COMMENT '账户名称',
    `password`    VARCHAR(100) NOT NULL COMMENT '账户密码',
    `account_roles`    VARCHAR(100) NOT NULL COMMENT '账户角色',
    `CREATED_TIME` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `CREATED_BY`   varchar(100) NOT NULL DEFAULT 'UNKNOWN',
    `UPDATED_TIME` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_BY`   varchar(100) NOT NULL DEFAULT 'UNKNOWN',
    PRIMARY KEY (`account_code`)
    ) ENGINE = InnoDB
    DEFAULT CHARSET = utf8mb4;


--  国际化信息
CREATE TABLE IF NOT EXISTS `tpl_i18n_t`(
    `I18N_ID`      VARCHAR(100) NOT NULL COMMENT 'KEY',
    `I18N_KEY`    VARCHAR(200) NOT NULL COMMENT 'KEY',
    `I18N_NAME`   VARCHAR(1000)          NOT NULL COMMENT 'NAME',
    `LANGUAGE`   VARCHAR(1000)          NOT NULL COMMENT 'LANGUAGE',
    `CREATED_TIME` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `CREATED_BY`   varchar(100) NOT NULL DEFAULT 'UNKNOWN',
    `UPDATED_TIME` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_BY`   varchar(100) NOT NULL DEFAULT 'UNKNOWN',
    PRIMARY KEY (`I18N_ID`)
    ) ENGINE = InnoDB
    DEFAULT CHARSET = utf8mb4;

-- LOOK UP CLASSIFY
CREATE TABLE IF NOT EXISTS `tpl_classify_t`(
    `CLASSIFY_CODE`    VARCHAR(200) NOT NULL COMMENT 'CLASSIFY_CODE',
    `CLASSIFY_NAME`   VARCHAR(200)          NOT NULL COMMENT 'CLASSIFY_NAME',
    `DESCRIPTION`   VARCHAR(1000)          NOT NULL COMMENT 'DESCRIPTION',
    `CREATED_TIME` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `CREATED_BY`   varchar(100) NOT NULL DEFAULT 'UNKNOWN',
    `UPDATED_TIME` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_BY`   varchar(100) NOT NULL DEFAULT 'UNKNOWN',
    PRIMARY KEY (`CLASSIFY_CODE`)
    ) ENGINE = InnoDB
    DEFAULT CHARSET = utf8mb4;

-- LOOK UP ITEM
CREATE TABLE IF NOT EXISTS `tpl_item_t`(
    `ITEM_ID`    VARCHAR(100) NOT NULL COMMENT '唯一ID',
    `ITEM_CODE`    VARCHAR(200) NOT NULL COMMENT '取值编码',
    `ITEM_NAME`    VARCHAR(500) NOT NULL COMMENT '显示名称',
    `LANGUAGE`    VARCHAR(50) NOT NULL COMMENT '语言',
    `ITEM_INDEX`    VARCHAR(100) NOT NULL COMMENT '排序值',
    `IS_ENABLED`    VARCHAR(10) NOT NULL COMMENT '是否开启',
    `DESCRIPTION`    VARCHAR(1000) NOT NULL COMMENT 'DESCRIPTION',

    `ITEM_ATTR1`    VARCHAR(1000) NOT NULL COMMENT '备用字段1',
    `ITEM_ATTR2`    VARCHAR(1000) NOT NULL COMMENT '备用字段2',
    `ITEM_ATTR3`    VARCHAR(1000) NOT NULL COMMENT '备用字段3',
    `ITEM_ATTR4`    VARCHAR(1000) NOT NULL COMMENT '备用字段4',
    `ITEM_ATTR5`    VARCHAR(1000) NOT NULL COMMENT '备用字段5',

    `CREATED_TIME` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `CREATED_BY`   varchar(100) NOT NULL DEFAULT 'UNKNOWN',
    `UPDATED_TIME` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_BY`   varchar(100) NOT NULL DEFAULT 'UNKNOWN',
    PRIMARY KEY (`ITEM_ID`)
    ) ENGINE = InnoDB
    DEFAULT CHARSET = utf8mb4;

-- 用户主表
CREATE TABLE IF NOT EXISTS `tpl_user_t`(
    `USER_ID`       VARCHAR(100)     NOT NULL ,
    `USER_ACCOUNT`    VARCHAR(100) NOT NULL COMMENT '用户账号',
    `USER_NAME`    VARCHAR(100) NOT NULL COMMENT '用户名称',
    `PASSWORD`    VARCHAR(100) NOT NULL COMMENT '用户密码',
    `CREATED_TIME` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `CREATED_BY`   varchar(100) NOT NULL DEFAULT 'UNKNOWN',
    `UPDATED_TIME` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_BY`   varchar(100) NOT NULL DEFAULT 'UNKNOWN',
    PRIMARY KEY (`USER_ID`)
    ) ENGINE = InnoDB
    DEFAULT CHARSET = utf8mb4;

-- 栏目表
CREATE TABLE IF NOT EXISTS `tpl_site_t`(
   `SITE_ID`    VARCHAR(100) NOT NULL COMMENT '栏目ID',
   `SITE_CODE`    VARCHAR(100) NOT NULL COMMENT '栏目编码用于关联国际化',
   `SITE_NAME`    VARCHAR(1000) NOT NULL COMMENT '默认栏目名称',
   `SITE_URL`    VARCHAR(100) NOT NULL COMMENT '访问URL',
   `IS_PUBLISH`    VARCHAR(100) NOT NULL COMMENT '是否发布',
   `OPEN_WAY`    VARCHAR(100) NOT NULL COMMENT '打开方式',
   `CREATED_TIME` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `CREATED_BY`   varchar(100) NOT NULL DEFAULT 'UNKNOWN',
   `UPDATED_TIME` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `UPDATED_BY`   varchar(100) NOT NULL DEFAULT 'UNKNOWN',
   PRIMARY KEY (`SITE_ID`)
   ) ENGINE = InnoDB
   DEFAULT CHARSET = utf8mb4;

-- 文件表

